### ISSUE TITLE
Cannot create crate

### ISSUE THREAD

**Issue by VozikCZE** [nulli0n/ExcellentCrates-spigot#127]
On clear installation (version 4.4.2 and NexEngine 2.2.12) on Paper 1.20.2 I cannot create crates.

It gives this error:
```[19:00:42 WARN]: [NexEngine] Task #119 for NexEngine v2.2.12 generated an exception
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
at su.nexmedia.engine.utils.ItemUtil.lambda$getSkullTexture$0(ItemUtil.java:105) ~[NexEngine.jar:?]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856) ~[?:?]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
at su.nexmedia.engine.utils.ItemUtil.getSkullTexture(ItemUtil.java:106) ~[NexEngine.jar:?]
at su.nexmedia.engine.api.config.JYML.setItem(JYML.java:375) ~[NexEngine.jar:?]
at su.nightexpress.excellentcrates.crate.impl.Crate.onSave(Crate.java:189) ~[ExcellentCrates-4.4.2.jar:?]
at su.nexmedia.engine.api.manager.AbstractConfigHolder.save(AbstractConfigHolder.java:43) ~[NexEngine.jar:?]
at su.nightexpress.excellentcrates.crate.CrateManager.create(CrateManager.java:181) ~[ExcellentCrates-4.4.2.jar:?]
at su.nightexpress.excellentcrates.crate.editor.CrateListEditor.lambda$new$1(CrateListEditor.java:39) ~[ExcellentCrates-4.4.2.jar:?]
at su.nexmedia.engine.editor.EditorListener.lambda$onChatText$0(EditorListener.java:43) ~[NexEngine.jar:?]
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.20.2.jar:git-Purpur-2072]
at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2072]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1495) ~[purpur-1.20.2.jar:git-Purpur-2072]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.20.2.jar:git-Purpur-2072]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[purpur-1.20.2.jar:git-Purpur-2072]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[purpur-1.20.2.jar:git-Purpur-2072]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[purpur-1.20.2.jar:git-Purpur-2072]
at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by nulli0n** [comment]
Redownload NexEngine.
