### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by daniel-skopek** [nulli0n/ExcellentCrates-spigot#131]
[23:21:49] [Server thread/ERROR]: Error occurred while enabling ExcellentCrates v5.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: su/nexmedia/engine/api/menu/link/Linked
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at su.nightexpress.excellentcrates.crate.CrateManager.onLoad(CrateManager.java:72) ~[ExcellentCrates-5.0.0.jar:?]
	at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:20) ~[NexEngine.jar:?]
	at su.nightexpress.excellentcrates.ExcellentCratesPlugin.enable(ExcellentCratesPlugin.java:64) ~[ExcellentCrates-5.0.0.jar:?]
	at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:215) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[NexEngine.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.nexmedia.engine.api.menu.link.Linked
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 25 more
[23:21:49] [Server thread/INFO]: [ExcellentCrates] Disabling ExcellentCrates v5.0.0
[23:21:49] [Server thread/ERROR]: Error occurred (in the plugin loader) while disabling ExcellentCrates v5.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: su/nexmedia/engine/api/menu/link/Linked
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:232) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:157) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at su.nightexpress.excellentcrates.crate.CrateManager.onShutdown(CrateManager.java:134) ~[ExcellentCrates-5.0.0.jar:?]
	at su.nexmedia.engine.api.manager.AbstractManager.shutdown(AbstractManager.java:26) ~[NexEngine.jar:?]
	at su.nightexpress.excellentcrates.ExcellentCratesPlugin.disable(ExcellentCratesPlugin.java:107) ~[ExcellentCrates-5.0.0.jar:?]
	at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:226) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:84) ~[NexEngine.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1102) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[pufferfish-1.20.1.jar:git-Pufferfish-26]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: su.nexmedia.engine.api.menu.link.Linked
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 28 more

**Comment by Sh3r1ffCZ** [comment]
Same problem

**Comment by itsTyrion** [comment]
just install nexengine

**Comment by Sh3r1ffCZ** [comment]
"I'm already using latest version of NexEngine (2.2.12)"

**Comment by Sh3r1ffCZ** [comment]
Ahh, ok. Thanks :3 I'm going to try
