### ISSUE TITLE
rewardWinLimits SQL error

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [nulli0n/ExcellentCrates-spigot#133]
[20:28:40 WARN]: java.sql.SQLException: Incorrect string value: '\xC4\x8D": {...' for column 'rewardWinLimits' at row 1
[20:28:40 WARN]: at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[20:28:40 WARN]: at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:28:40 WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[20:28:40 WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[20:28:40 WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
[20:28:40 WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
[20:28:40 WARN]: at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
[20:28:40 WARN]: at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[20:28:40 WARN]: at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[20:28:40 WARN]: at NexEngine.jar//su.nexmedia.engine.api.data.sql.SQLQueries.executeStatement(SQLQueries.java:73)
[20:28:40 WARN]: at NexEngine.jar//su.nexmedia.engine.api.data.sql.executor.UpdateQueryExecutor.execute(UpdateQueryExecutor.java:69)
[20:28:40 WARN]: at NexEngine.jar//su.nexmedia.engine.api.data.AbstractDataHandler.update(AbstractDataHandler.java:163)
[20:28:40 WARN]: at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUserDataHandler.saveUser(AbstractUserDataHandler.java:143)
[20:28:40 WARN]: at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUserManager.lambda$saveUser$3(AbstractUserManager.java:140)
[20:28:40 WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:103)
[20:28:40 WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:28:40 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:28:40 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:28:40 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:28:40 WARN]: at java.base/java.lang.Thread.run(Thread.java:1623)

This error only occurs when I set a limit on a reward.
      Win_Limits:
        Amount: 2
        Cooldown: 86400

Plugin: ExcellentCrates-4.4.2.jar
Java: Java 20.0.1 Oracle
Server: 1.20.1 (pufferfish-paperclip-1.20.1-R0.1-SNAPSHOT-reobf)

**Comment by nulli0n** [comment]
don't use special symbols in crate and reward ids.
