### ISSUE TITLE
I can't open the menus of the editor (/crates editor)

### ISSUE THREAD

**Issue by eZomb** [nulli0n/ExcellentCrates-spigot#135]
I'm using Catserver.jar Version 1.18.2

this is what appears in the console:
[15:02:46] [Server thread/WARN] [su.nightexpress.excellentcrates.ExcellentCratesPlugin]: [ExcellentCrates] Task #198 for ExcellentCrates v5.0.0 generated an exception
java.lang.NullPointerException: Cannot invoke "su.nightexpress.excellentcrates.key.KeyManager.plugin()" because "keyManager" is null
	at su.nightexpress.excellentcrates.key.editor.KeyListEditor.<init>(KeyListEditor.java:29) ~[?:?]
	at su.nightexpress.excellentcrates.editor.EditorMainMenu.getKeysEditor(EditorMainMenu.java:56) ~[?:?]
	at su.nightexpress.excellentcrates.editor.EditorMainMenu.lambda$new$2(EditorMainMenu.java:28) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:83) ~[forge-1.18.2-40.2.4-universal.jar%23118!/:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.18.2-40.2.4-universal.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1159) ~[server-1.18.2-20220404.173914-srg.jar%23113!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:397) ~[server-1.18.2-20220404.173914-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1112) ~[server-1.18.2-20220404.173914-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:952) ~[server-1.18.2-20220404.173914-srg.jar%23113!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312) ~[server-1.18.2-20220404.173914-srg.jar%23113!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by nulli0n** [comment]
Forge is not supported. Stop use mods + plugins server software, your problems will never ends with it.
