### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.yaml.snakeyaml.nodes.Node.getNodeId()" because "node" is null

### ISSUE THREAD

**Issue by DexterSK** [nulli0n/ExcellentCrates-spigot#140]
Idk why this happens, it happens just sometime 

```
[19:26:14 WARN]: [ExcellentCrates] Plugin ExcellentCrates v5.0.0 generated an exception while executing task 51133087
java.lang.NullPointerException: Cannot invoke "org.yaml.snakeyaml.nodes.Node.getNodeId()" because "node" is null
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:129) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:146) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:156) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.serializer.Serializer.anchorNode(Serializer.java:156) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.serializer.Serializer.serialize(Serializer.java:118) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.Yaml.serialize(Yaml.java:371) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:91) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:65) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at su.nexmedia.engine.api.config.JYML.save(JYML.java:116) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.config.JYML.saveChanges(JYML.java:126) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.crate.impl.Crate.saveLastOpenData(Crate.java:225) ~[ExcellentCrates-5.0.0.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateManager.lambda$interactCrate$6(CrateManager.java:346) ~[ExcellentCrates-5.0.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2083]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WMGameLive** [comment]
I got same error on this plugin, and even my own plugin has the same error, it seems that both are saving config in a task, but I also don't know why this happens.

**Comment by dinobossytnew** [comment]
test paper software

**Comment by nulli0n** [comment]
Try update your server softawre.
