### ISSUE TITLE
[ExcellentCrates] Plugin ExcellentCrates v5.0.0 generated an exception while executing task 85

### ISSUE THREAD

**Issue by Typowabrzozaa** [nulli0n/ExcellentCrates-spigot#145]
[23:13:45 WARN]: [ExcellentCrates] Plugin ExcellentCrates v5.0.0 generated an exception while executing task 85
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketContainer
        at su.nightexpress.excellentcrates.hologram.impl.HologramInternalHandler.spawnHologram(HologramInternalHandler.java:110) ~[ExcellentCrates-LATEST-[5.0.0].jar:?]
        at su.nightexpress.excellentcrates.hologram.impl.HologramInternalHandler.create(HologramInternalHandler.java:76) ~[ExcellentCrates-LATEST-[5.0.0].jar:?]
        at su.nightexpress.excellentcrates.crate.impl.Crate.createHologram(Crate.java:257) ~[ExcellentCrates-LATEST-[5.0.0].jar:?]
        at su.nightexpress.excellentcrates.crate.impl.Crate.updateHologram(Crate.java:269) ~[ExcellentCrates-LATEST-[5.0.0].jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at su.nightexpress.excellentcrates.crate.task.HologramUpdateTask.action(HologramUpdateTask.java:17) ~[ExcellentCrates-LATEST-[5.0.0].jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-272]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-272]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketContainer
        ... 12 more

**Comment by nulli0n** [comment]
Update ProtocolLib to the latest dev build.
