### ISSUE TITLE
Error while opening crates

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [nulli0n/ExcellentCrates-spigot#15]
MC 1.18.2 purpur-1596
ExcellentCrates v4.0.3.6
```
10.04 03:52:56 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:56 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:56 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:56 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:56 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:56 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:56 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
10.04 03:52:56 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:56 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:56 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:56 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Multicraft] Skipped 44 lines due to rate limit (100/s)
10.04 03:52:56 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:56 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:56 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:56 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:56 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:56 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:56 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:56 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
10.04 03:52:57 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:57 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:57 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:57 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:57 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
10.04 03:52:57 [Server] INFO [ChatControlRed] [zwykly] ketrab__: XD
10.04 03:52:57 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:57 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:57 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:57 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:57 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
10.04 03:52:57 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:57 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:57 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:57 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:57 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:57 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
10.04 03:52:58 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:58 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:58 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:58 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:58 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
10.04 03:52:58 [Server] WARN [ExcellentCrates] Task #74168 for ExcellentCrates v4.0.3.6 generated an exception
10.04 03:52:58 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 4
10.04 03:52:58 [Server] INFO at java.util.Arrays$ArrayList.set(Arrays.java:4170) ~[?:?]
10.04 03:52:58 [Server] INFO at net.minecraft.core.NonNullList.set(NonNullList.java:54) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.world.inventory.CraftingContainer.setItem(CraftingContainer.java:140) ~[?:?]
10.04 03:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.setItem(CraftInventoryCrafting.java:79) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.spinReward(CrateSpinAnimation.java:365) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:58 [Server] INFO at su.nightexpress.excellentcrates.animation.CrateSpinAnimation$SpinTask.run(CrateSpinAnimation.java:334) ~[ExcellentCrates-4.0.3.6.jar:?]
10.04 03:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1558) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1596]
10.04 03:52:58 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1596]

```

**Comment by nulli0n** [comment]
Error in your animation config, reset it or reconfigure.
