### ISSUE TITLE
Error crashing my server.

### ISSUE THREAD

**Issue by SliderKP** [nulli0n/ExcellentCrates-spigot#162]
im getting this error:

[19:58:30 WARN]: java.lang.Throwable
[19:58:30 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUserManager.getUserData(AbstractUserManager.java:63)
[19:58:30 WARN]:        at ExcellentCrates-5.0.0.jar//su.nightexpress.excellentcrates.key.KeyManager.giveKeysOnHold(KeyManager.java:179)
[19:58:30 WARN]:        at ExcellentCrates-5.0.0.jar//su.nightexpress.excellentcrates.key.KeyListener.onUserLoad(KeyListener.java:34)
[19:58:30 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1049.execute(Unknown Source)
[19:58:30 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[19:58:30 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[19:58:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:58:30 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:58:30 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[19:58:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[19:58:30 WARN]:        at net.minecraft.server.players.PlayerList.a(PlayerList.java:344)
[19:58:30 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[19:58:30 WARN]:        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[19:58:30 WARN]:        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[19:58:30 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[19:58:30 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:58:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:58:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1462)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[19:58:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1439)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[19:58:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1513)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1217)
[19:58:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:58:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[19:58:30 WARN]: [ExcellentCrates] Main thread user data load for '5ea69eb1-19e7-48e8-8e91-8f3b6b3609d2' aka 'Jordy_PsiCrazy'.

minecraft version: 1.20.4 pufferfish-44 (fork paper)
excelent crates 5.0.0
latest dev protocollib

**Comment by dinobossytnew** [comment]
give full log.

**Comment by nulli0n** [comment]
Fixed in v5.2.0
