### ISSUE TITLE
Crates generating errors on each player opening

### ISSUE THREAD

**Issue by KoalaServers** [nulli0n/ExcellentCrates-spigot#197]
```
! [Thu 18:51:40 WARN  ExcellentCrates] Task #9303228 for ExcellentCrates v5.2.2.3 generated an exception
java.lang.NoSuchMethodError: 'su.nightexpress.nightcore.util.text.WrappedMessage su.nightexpress.nightcore.util.text.NightMessage.create(java.lang.String, su.nightexpress.nightcore.util.text.tag.TagPool)'
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.CrateLogger.log(CrateLogger.java:38)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.CrateLogger.logReward(CrateLogger.java:32)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.crate.impl.Reward.give(Reward.java:366)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.spinner.RewardSpinner.checkRewards(RewardSpinner.java:105)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.spinner.RewardSpinner.onStop(RewardSpinner.java:88)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.Runnable.stop(Runnable.java:28)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.Runnable.tick(Runnable.java:42)
    at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.AbstractOpening.onTick(AbstractOpening.java:82)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.inventory.InventoryOpening.onTick(InventoryOpening.java:86)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.Runnable.tick(Runnable.java:47)
    at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4783)
    at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
    at ExcellentCrates-5.2.2.3.jar//su.nightexpress.excellentcrates.opening.OpeningManager.tickOpenings(OpeningManager.java:82)
    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThrea
```

**Comment by nulli0n** [comment]
Fixed in v5.3.0
