### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Illustive** [nulli0n/ExcellentCrates-spigot#206]
[22:00:08] [Server thread/ERROR]: Error occurred while enabling ExcellentCrates v5.3.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'void su.nightexpress.nightcore.util.wrapper.UniParticle.validateData()'
	at ExcellentCrates-5.3.1.jar/su.nightexpress.excellentcrates.crate.impl.Crate.setEffectParticle(Crate.java:616) ~[ExcellentCrates-5.3.1.jar:?]
	at ExcellentCrates-5.3.1.jar/su.nightexpress.excellentcrates.crate.impl.Crate.onLoad(Crate.java:157) ~[ExcellentCrates-5.3.1.jar:?]
	at nightcore-2.6.3.jar/su.nightexpress.nightcore.manager.AbstractFileData.load(AbstractFileData.java:36) ~[nightcore-2.6.3.jar:?]
	at ExcellentCrates-5.3.1.jar/su.nightexpress.excellentcrates.crate.CrateManager.loadCrate(CrateManager.java:149) ~[ExcellentCrates-5.3.1.jar:?]
	at ExcellentCrates-5.3.1.jar/su.nightexpress.excellentcrates.crate.CrateManager.loadCrates(CrateManager.java:141) ~[ExcellentCrates-5.3.1.jar:?]
	at ExcellentCrates-5.3.1.jar/su.nightexpress.excellentcrates.crate.CrateManager.onLoad(CrateManager.java:66) ~[ExcellentCrates-5.3.1.jar:?]
	at nightcore-2.6.3.jar/su.nightexpress.nightcore.manager.SimpleManager.setup(SimpleManager.java:20) ~[nightcore-2.6.3.jar:?]
	at ExcellentCrates-5.3.1.jar/su.nightexpress.excellentcrates.CratesPlugin.enable(CratesPlugin.java:88) ~[ExcellentCrates-5.3.1.jar:?]
	at nightcore-2.6.3.jar/su.nightexpress.nightcore.NightPlugin.loadManagers(NightPlugin.java:150) ~[nightcore-2.6.3.jar:?]
	at nightcore-2.6.3.jar/su.nightexpress.nightcore.NightDataPlugin.loadManagers(NightDataPlugin.java:12) ~[nightcore-2.6.3.jar:?]
	at nightcore-2.6.3.jar/su.nightexpress.nightcore.NightPlugin.onEnable(NightPlugin.java:56) ~[nightcore-2.6.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2280-930003b]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.jar:1.21-2280-930003b]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.jar:1.21-2280-930003b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:00:08] [Server thread/INFO]: [ExcellentCrates] Disabling ExcellentCrates v5.3.1

**Comment by nulli0n** [comment]
https://github.com/nulli0n/nightcore-spigot/releases/tag/v2.6.3-updated
