### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by GM-Ricker** [nulli0n/ExcellentCrates-spigot#233]
[20:39:50 WARN]: [ExcellentCrates] Task #71 for ExcellentCrates v5.3.5 generated an exception
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:BLOCK_NOTE_BLOCK_BELL
        at net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:278) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.resources.ResourceLocation.withDefaultNamespace(ResourceLocation.java:68) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.resources.ResourceLocation.bySeparator(ResourceLocation.java:92) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.resources.ResourceLocation.parse(ResourceLocation.java:64) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at org.bukkit.craftbukkit.entity.CraftPlayer.playSound(CraftPlayer.java:843) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at org.bukkit.craftbukkit.entity.CraftPlayer.playSound(CraftPlayer.java:829) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at org.bukkit.craftbukkit.entity.CraftPlayer.playSound(CraftPlayer.java:819) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at nightcore-2.7.2.jar/su.nightexpress.nightcore.util.wrapper.UniSound.play(UniSound.java:78) ~[nightcore-2.7.2.jar:?]
        at ExcellentCrates-5.3.5.jar/su.nightexpress.excellentcrates.opening.AbstractSpinner.onTick(AbstractSpinner.java:57) ~[ExcellentCrates-5.3.5.jar:?]
        at ExcellentCrates-5.3.5.jar/su.nightexpress.excellentcrates.opening.Runnable.tick(Runnable.java:47) ~[ExcellentCrates-5.3.5.jar:?]
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833) ~[?:?]
        at ExcellentCrates-5.3.5.jar/su.nightexpress.excellentcrates.opening.AbstractOpening.onTick(AbstractOpening.java:83) ~[ExcellentCrates-5.3.5.jar:?]
        at ExcellentCrates-5.3.5.jar/su.nightexpress.excellentcrates.opening.inventory.InventoryOpening.onTick(InventoryOpening.java:87) ~[ExcellentCrates-5.3.5.jar:?]
        at ExcellentCrates-5.3.5.jar/su.nightexpress.excellentcrates.opening.Runnable.tick(Runnable.java:47) ~[ExcellentCrates-5.3.5.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at ExcellentCrates-5.3.5.jar/su.nightexpress.excellentcrates.opening.OpeningManager.tickOpenings(OpeningManager.java:90) ~[ExcellentCrates-5.3.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1801) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1662) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1328) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-14-fcb6c72]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by GM-Ricker** [comment]
solved
