### ISSUE TITLE
Some Crates do not convert properly from GoldenCrates config

### ISSUE THREAD

**Issue by FrontierDevelopment** [nulli0n/ExcellentCrates-spigot#3]
After converting from GoldenCrates, most of my Crates were successfully converted. However a few of them throw an error in console when trying to preview. I have checked in the "/crate editor" and all rewards show as well as in the config all rewards are there.

Below I will add the error from console, as well as a screenshot of what the crate preview used to look like when using GoldenCrates.

![image](https://user-images.githubusercontent.com/92769575/150687657-e0a09bfd-c65c-47b4-8d21-379c09c44959.png)

`[11:10:38 ERROR]: Could not pass event PlayerInteractEvent to ExcellentCrates v4.0.3.3
java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 0)
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.createInventory(CraftServer.java:2088) ~[paper-1.18.1.jar:git-Paper-167]
        at su.nexmedia.engine.api.menu.IMenu.getInventory(IMenu.java:116) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.menu.IMenu.open(IMenu.java:144) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.crate.Crate.openPreview(Crate.java:325) ~[ExcellentCrates-4.0.3.3.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateManager.interactCrate(CrateManager.java:180) ~[ExcellentCrates-4.0.3.3.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateListener.onCrateUse(CrateListener.java:65) ~[ExcellentCrates-4.0.3.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor447.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-167]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[paper-1.18.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:506) ~[paper-1.18.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:501) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:219) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1762) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by FrontierDevelopment** [comment]
Quick add, they also register as crates, as when I right click on them they either say:

ExcellentCrates >> You don't have a key for this crate!      OR     The crate will actually open properly

I have also noticed that when converting from GoldenCrates, the command and item from the rewards will not be there.
For example in my Vote Crate, when I open the crate, it shows what I won, but nothing happens. I looked at the crate editor and seems like none of the actual rewards got carried over, just the item and display name and some other info for the crate

**Comment by nulli0n** [comment]
You have to update preview configs to the new config format, see config details here: http://77.222.60.131:8080/plugin/excellentcrates/config/preview/example

Converter seems to be working fine for me, make sure you're using the latest version of it.
