### ISSUE TITLE
With the auto-donate system, it gives an error

### ISSUE THREAD

**Issue by Kostya-An** [nulli0n/ExcellentCrates-spigot#32]
The player bought a case for donation, but an error occurred during the issuance.
`[10:02:02] [Server thread/WARN]: Unexpected exception while parsing console command "crate give v CrateExample 1 inhit"
org.bukkit.command.CommandException: Unhandled exception executing command 'crate' in plugin CrazyCrates v1.11.5-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-386]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.lambda$runCommand$3(DedicatedServer.java:773) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_18_R2.command.CraftRemoteConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_18_R2.command.CraftRemoteConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader java.net.URLClassLoader @5c29bfd)
	at com.badbones69.crazycrates.Methods.permCheck(Methods.java:112) ~[Crazy-Crates-1.18-1.19-v1.11.5-SNAPSHOT (1).jar:?]
	at com.badbones69.crazycrates.commands.CCCommand.onCommand(CCCommand.java:595) ~[Crazy-Crates-1.18-1.19-v1.11.5-SNAPSHOT (1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 19 more`
How to fix it?

**Comment by nulli0n** [comment]
This is not even from this crates plugin. Wtf?
