### ISSUE TITLE
Cannot invoke because "CitizensHook.listeners" is null

### ISSUE THREAD

**Issue by nickkeane** [nulli0n/ExcellentCrates-spigot#47]
java.lang.NullPointerException: Cannot invoke "java.util.Map.computeIfAbsent(Object, java.util.function.Function)" because "su.nexmedia.engine.hooks.external.citizens.CitizensHook.listeners" is null
  at su.nexmedia.engine.hooks.external.citizens.CitizensHook.getListeners(CitizensHook.java:52) ~[?:?]
  at su.nexmedia.engine.hooks.external.citizens.CitizensHook.addListener(CitizensHook.java:47) ~[?:?]
  at su.nightexpress.excellentcrates.ExcellentCrates.registerHooks(ExcellentCrates.java:124) ~[?:?]
  at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:159) ~[?:?]
  at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:74) ~[?:?]
  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
  at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-131]
  at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-131]
  at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-131]
  at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-131]
  at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-131]
  at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1125) ~[paper-1.19.2.jar:git-Paper-131]
  at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-131]
  at java.lang.Thread.run(Thread.java:833) [?:?]

PaperMC: 1.19.2 b131
NexEngine: v2.2.0 b18/06/2022
ExcellentCrates: v4.0.5
Citizens: 2.0.30 b2666

**Comment by SnowzNZ** [comment]
How was it solved?
