### ISSUE TITLE
Error when player join server

### ISSUE THREAD

**Issue by ZappySK** [nulli0n/ExcellentCrates-spigot#48]
Could not pass event AsyncPlayerPreLoginEvent to ExcellentCrates v4.0.5
java.lang.AbstractMethodError: Receiver class su.nightexpress.excellentcrates.data.UserManager does not define or inherit an implementation of the resolved method 'abstract su.nexmedia.engine.api.data.AbstractUser createData(java.util.UUID, java.lang.String)' of abstract class su.nexmedia.engine.api.data.AbstractUserManager.
at su.nexmedia.engine.api.data.AbstractUserManager$PlayerListener.onUserLogin(AbstractUserManager.java:227) ~[NexEngine.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-133]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:442) ~[?:?]
at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:321) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
Install latest NexEngine: https://github.com/nulli0n/NexEngine-spigot/releases
