### ISSUE TITLE
Excellent Crates just doesn't work (1.19.2)

### ISSUE THREAD

**Issue by kokqi** [nulli0n/ExcellentCrates-spigot#61]
I received this error

[09:48:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[09:48:17 INFO]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@7cc9e4bd
[09:48:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[09:48:17 INFO]: [ExcellentCrates] Loaded 5 animation configs.
[09:48:17 ERROR]: Error occurred while enabling ExcellentCrates v4.0.6 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack su.nexmedia.engine.api.config.JYML.getItem(java.lang.String, java.lang.String)'
        at su.nightexpress.excellentcrates.key.CrateKey.<init>(CrateKey.java:51) ~[ExcellentCrates-4.0.6.jar:?]
        at su.nightexpress.excellentcrates.key.KeyManager.onLoad(KeyManager.java:50) ~[ExcellentCrates-4.0.6.jar:?]
        at su.nexmedia.engine.api.manager.AbstractManager.setup(AbstractManager.java:21) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.ExcellentCrates.enable(ExcellentCrates.java:63) ~[ExcellentCrates-4.0.6.jar:?]
        at su.nexmedia.engine.NexPlugin.loadManagers(NexPlugin.java:212) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:78) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-271]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-271]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-271]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:48:17 INFO]: [ExcellentCrates] Disabling ExcellentCrates v4.0.6
[09:48:17 INFO]: [ExcellentCrates] [Citizens Hook] Unregistered listeners
[09:48:17 INFO]: [ExcellentCrates] Auto-save: Saved 0 online users | 0 offline users.
[09:48:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown initiated...
[09:48:17 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Shutdown completed.

**Comment by kokqi** [comment]
ah I see, citizens plugin issue

**Comment by Zynaxwastaken** [comment]
I am also getting this error on 1.19.2

**Comment by nulli0n** [comment]
Update NexEngine and download the latest plugin version.
