### ISSUE TITLE
Keys are not getting removed when using the Crate. Default Config

### ISSUE THREAD

**Issue by IWolfZZ** [nulli0n/ExcellentCrates-spigot#85]
Using the Lastest Version as of right now (4.1.6) and with NexEngine 2.2.9

Crates break randomly and players are able to use the key infinitely, even if they only have 1 key. 

[23:45:14 ERROR]: Could not pass event PlayerInteractEvent to ExcellentCrates v4.1.6
java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 0)
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[commons-lang-2.6.jar:2.6]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.createInventory(CraftServer.java:2141) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at su.nexmedia.engine.api.menu.AbstractMenu.createInventory(AbstractMenu.java:236) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.menu.AbstractMenu.open(AbstractMenu.java:127) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.crate.Crate.openPreview(Crate.java:270) ~[ExcellentCrates-4.1.6.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateManager.interactCrate(CrateManager.java:208) ~[ExcellentCrates-4.1.6.jar:?]
        at su.nightexpress.excellentcrates.crate.CrateListener.onCrateUse(CrateListener.java:67) ~[ExcellentCrates-4.1.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor423.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-59]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:198) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1872) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-59]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by TylBurxyz** [comment]
'java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 0)'
It looks like you haven't set the "Size:" in the crate.yml

**Comment by nulli0n** [comment]
Fixed in the latest version.
