### ISSUE TITLE
1.18.2 support

### ISSUE THREAD

**Issue by SnickoDeadMC** [nulli0n/ExcellentCrates-spigot#9]
ExcellentCrates/NexEngine doesn't work on 1.18.2

`[15:53:16 INFO]: [NexEngine] Enabling NexEngine v2.1.1 build-26/02/2022
[15:53:16 WARN]: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_18_R2
[15:53:16 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:273)
[15:53:16 WARN]:        at NexEngine.jar//su.nexmedia.engine.Version.valueOf(Version.java:6)
[15:53:16 WARN]:        at NexEngine.jar//su.nexmedia.engine.Version.<clinit>(Version.java:19)
[15:53:16 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:99)
[15:53:16 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:70)
[15:53:16 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:67)
[15:53:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:53:16 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:53:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[15:53:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[15:53:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[15:53:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:289)
[15:53:16 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[15:53:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[15:53:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:53:16 ERROR]: Error occurred while enabling NexEngine v2.1.1 build-26/02/2022 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:99) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:70) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:67) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-228]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-228]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-228]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_18_R2
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[NexEngine.jar:?]
        at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[NexEngine.jar:?]
        ... 12 more
[15:53:16 INFO]: [NexEngine] Disabling NexEngine v2.1.1 build-26/02/2022`

**Comment by PappoYT** [comment]
Same problem here.

Today I've updated to Paper 1.18.2 build 235 and get those errors:

```
[Server thread/ERROR]: Error occurred while enabling NexEngine v2.1.1 build-26/02/2022 (Is it up to date?) java.lang.ExceptionInInitializerError: null

[Server thread/ERROR]: Error occurred while enabling ExcellentCrates v4.0.3.6 (Is it up to date?)
java.lang.NoClassDefFoundError: su/nexmedia/engine/hooks/Hooks

[Server thread/ERROR]: Error occurred while disabling ExcellentCrates v4.0.3.6 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
```

I'm using ExcellentCrates-4.0.3.6.jar

Link to log: [https://mclo.gs/LfQWutp](https://mclo.gs/LfQWutp)

**Comment by nulli0n** [comment]
Update NexEngine.
