### ISSUE TITLE
error

### ISSUE THREAD

**Issue by waumiller1818** [nulli0n/ExcellentCrates-spigot#90]
19:37:04 WARN]: [ExcellentCrates] Task #265354 for ExcellentCrates v4.1.10 generated an exception
java.lang.NoSuchMethodError: 'su.nexmedia.engine.api.menu.item.MenuItem su.nexmedia.engine.api.menu.impl.Menu.addItem(su.nexmedia.engine.api.menu.item.MenuItem)'
        at su.nightexpress.excellentcrates.crate.editor.CrateListEditor.onPrepare(CrateListEditor.java:53) ~[ExcellentCrates-4.1.10.jar:?]
        at su.nexmedia.engine.api.menu.impl.Menu.open(Menu.java:82) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.editor.EditorMainMenu.lambda$new$0(EditorMainMenu.java:23) ~[ExcellentCrates-4.1.10.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:103) ~[paper-1.19.4.jar:git-Paper-501]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-501]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-501]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
https://github.com/nulli0n/NexEngine-spigot/releases/tag/v2.2.10
